# Generated by Django 6.0.2 on 2026-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=20),
        ),
    ]
