# Generated by Django 6.0.2 on 2026-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_earned',
            field=models.IntegerField(default=0),
        ),
    ]
