# Generated by Django 6.0.2 on 2026-03-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_application_applied_at_job_created_at_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('Completed', 'Completed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
