# Generated by Django 6.0.2 on 2026-03-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
